name: Build and Push RStudio Docker Image

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and tag Docker image
      run: |
        docker build -t ghcr.io/louisaslett/dssm:4.5.2 -t ghcr.io/louisaslett/dssm:latest ./docker

    - name: Push Docker image to GHCR
      run: |
        docker push --all-tags ghcr.io/louisaslett/dssm

